http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: [
      '/signin',
      '/signup'
    ]
  users:
    host: localhost
    paths: [
      '/user'
    ]
  product:
    host: localhost
    paths: [
      '/product/all',
      '/product/:id',
      '/product/name/:name',
      '/product/category/:category',
      '/product/create',
      '/product/delete/:id',
      '/product/update'
    ]
  seller:
    host: localhost
    paths: [
      '/seller/all',
      '/seller/:id',
      '/seller/create',
      '/seller/delete/:id'
    ]
  client:
    host: localhost
    paths: [
      '/client/all',
      '/client/:id',
      '/client/create',
      '/client/delete/:id'
    ]
  order:
    host: localhost
    paths: [
      '/order/all',
      '/order/:id',
      '/order/client/:cid',
      '/order/create',
      '/order/delete/:id'
    ]
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authService:
    url: 'http://localhost:8888'
  usersService:
    url: 'http://localhost:9999'
  productService:
    url: 'http://localhost:9090'
  sellerService:
    url: 'http://localhost:9092'
  clientService:
    url: 'http://localhost:9091'
  orderService:
    url: 'http://localhost:9093'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  authPepeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authService 
              changeOrigin: true
  usersPepeline:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true
  productPepeline:
    apiEndpoints:
      - product
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productService 
              changeOrigin: true
  sellerPepeline:
    apiEndpoints:
      - seller
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sellerService 
              changeOrigin: true
  clientPepeline:
    apiEndpoints:
      - client
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: clientService 
              changeOrigin: true
  orderPepeline:
    apiEndpoints:
      - order
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: orderService 
              changeOrigin: true
